# Site settings
title: Pedro Santana 
description: Lucas Ferraz
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pedro Santana
user_description: Olá, Meu nome é Pedro Henrique de Santana tenho 17 anos e sou de Guarulhos São Paulo. Gosto de música principalmente 
RAP/ Hip-hop. 

user_title: Desenvolvedor e Designer
email: pedroprog@uninove.edu.br
github_username:  DotyJJ


# Google-analytics
google-analytics:
  id: "UA-97251498-1"
  
# Google-AdSense
google_ad_client: "ca-pub-8284956553090163"

exclude: ['package.json', 'src' , 'node_modules']
