# Site settings
title: Lucas Ferraz
description: Lucas Ferraz
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lucas Ferraz
user_description: Meu nome é Lucas tenho 17 anos sou programador e designer. Gosto muito de esportes, músicas, jogos de raciocinio e do mundo virtual.
user_title: Software Developer
email: ulucas@uninove.edu.br
twitter_username: uniteluks
github_username:  eulucas
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
